<a href="https://colab.research.google.com/github/pxs1990/Data_Science_projects/blob/main/ds_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy:**

# **1. Creating Arrays**

In [3]:
import numpy as np

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
np.arange(10) # 0..9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0, 1, 5)         # 5 numbers evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(3,3)

array([[0.34020318, 0.58913062, 0.36886086],
       [0.9106811 , 0.17880807, 0.82139749],
       [0.50591461, 0.015878  , 0.4525879 ]])

In [12]:
np.random.randint(0, 10, 5)

array([3, 5, 7, 2, 1])

# **2. Array Attributes**

In [14]:
arr=np.ones((2,2))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 2)
4
float64


# **3. Reshaping Arrays**

In [16]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
arr2 = arr.reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
flat = arr2.flatten() # copy of original
print(flat)

[0 1 2 3 4 5 6 7 8]


In [19]:
rav = arr2.ravel() # not a copy. change here changes original too.
print(rav)


[0 1 2 3 4 5 6 7 8]


In [20]:
print(arr2.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


# **4. Indexing & Slicing**

In [ ]:
arr[0]
arr[1:4]
arr[:, 0]
arr[1:3, 2:4]
arr[arr > 5] # boolean filter

# **5. Math Operations**

In [ ]:
np.add(a, b)
np.subtract(a, b)
np.multiply(a, b)
np.divide(a, b)
np.power(a, 2)

np.sqrt(arr)
np.exp(arr)
np.log(arr)

# **6. Aggregations**

In [ ]:
np.sum(arr)
np.mean(arr)
np.std(arr)
np.var(arr)
np.min(arr)
np.max(arr)
np.argmin(arr) # index of max val
np.argmax(arr)
np.cumsum(arr) # cumulative sum

# **7. Broadcasting**

In [21]:
arr = np.array([1, 2, 3])
print(arr + 5)
print(arr + [1,2,3])
print(arr * [1,2,3])

[6 7 8]
[2 4 6]
[1 4 9]


# **8. Stacking & Concatenation**

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate([a, b]) # joins along an existing array

array([1, 2, 3, 4, 5, 6])

In [23]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.concatenate([a, b]) # default axis=0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.concatenate([a, b],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack([a, b])


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack([a, b])


array([1, 2, 3, 4, 5, 6])

# **9. Sorting & Unique**

In [30]:
arr = np.array([5, 1, 4, 2])

arr1=np.sort(arr)
print(arr1)
# np.sort(arr)[::-1] for descending order

[1 2 4 5]


In [31]:
np.argsort(arr) # index that would sort the arr

array([1, 3, 2, 0])

In [32]:
np.unique(arr) # removes duplicates

array([1, 2, 4, 5])

# **10. Linear Algebra**

In [ ]:
np.dot(a, b)
np.matmul(a, b)
np.linalg.inv(A)
np.linalg.det(A)
np.linalg.eig(A)

# **11. Random Module**

In [33]:
np.random.seed(42) # reproducibility

In [42]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [43]:
np.random.randn(3)

array([-1.11188012,  0.31890218,  0.27904129])

In [44]:
np.random.randint(0, 10, 5)

array([7, 2, 5, 4, 1])

In [47]:
arr=np.arange(10)
np.random.choice(arr)

np.int64(1)